version: '3.9'

x-aio-credentials-pool-common-environment: &aio-credentials-pool-common-environment
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: postgres


services:
  in_memory_credentials_pool:
    container_name: in_memory_credentials_pool
    build: .
    command: python3 worker.py --workers 40 --pool_type in_memory
    environment: *aio-credentials-pool-common-environment

  persistent_credentials_pool:
    container_name: persistent_credentials_pool
    build: .
    entrypoint: ["./run_migrations.sh"]
    command: python3 worker.py --workers 40 --pool_type persistent
    environment: *aio-credentials-pool-common-environment
    volumes:
      - './aio_credentials_pool:/opt/aio_credentials_pool/.'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.9-alpine3.18
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  postgres:
