[tool.ruff]
select = ["ALL"]
ignore = [
    "ANN", "EM101", "TRY003", "INP001", "D", "S101", "A003", "G004", "D211", "D213",
    "COM812", "ISC001", "S311", "S106", "PLR2004", "E712", "DTZ003", "FBT001",
]
line-length = 120
target-version = "py311"
format.quote-style = "single"

[tool.ruff.flake8-quotes]
inline-quotes = "single"

[tool.ruff.isort]
known-first-party = [
    'models', 'base_credentials_pool', 'persistent_credentials_pool',
    'in_memory_credentials_pool', 'settings',
]
known-third-party = ['alembic']

[tool.ruff.mccabe]
max-complexity = 10

