"""Add date_last_usage field

Revision ID: 2e4ffe052cd8
Revises: f67bda6eade3
Create Date: 2023-12-16 19:03:05.481516

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2e4ffe052cd8'
down_revision = 'f67bda6eade3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('date_last_usage', sa.DateTime(), nullable=True))
    op.create_index(
        op.f('ix_credentials_date_last_usage'),
        'credentials',
        ['date_last_usage'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_date_last_usage'), table_name='credentials')
    op.drop_column('credentials', 'date_last_usage')
    # ### end Alembic commands ###
