"""Load credentials fixture

Revision ID: 890872dbc09f
Revises: 70f77cac5a07
Create Date: 2023-12-16 17:05:53.996947

"""
import json
from pathlib import Path

from alembic import op
from models import Credential


# revision identifiers, used by Alembic.
revision = "890872dbc09f"
down_revision = "70f77cac5a07"
branch_labels = None
depends_on = None


CREDENTIALS_JSON_PATH = (
    Path(__file__).parent.parent.parent / "fixtures" / "credentials.json"
)


def load_credentials_data():
    with open(CREDENTIALS_JSON_PATH, "r") as file:
        data = json.load(file)
        op.bulk_insert(Credential.__table__, data)


def upgrade() -> None:
    load_credentials_data()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
