"""Add index to username field

Revision ID: ed4a93f9b7a3
Revises: 2e4ffe052cd8
Create Date: 2023-12-17 17:36:23.681168

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ed4a93f9b7a3'
down_revision = '2e4ffe052cd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('credentials_username_key', 'credentials', type_='unique')
    op.create_index(op.f('ix_credentials_username'), 'credentials', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_username'), table_name='credentials')
    op.create_unique_constraint('credentials_username_key', 'credentials', ['username'])
    # ### end Alembic commands ###
